global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'surfudeenbe@gmail.com'
  smtp_auth_username: 'surfudeenbe@gmail.com'
  smtp_auth_password: 'bkul biiu isot vzxc'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: 'surfudeenbe@gmail.com'
        send_resolved: true

